
const bizType = {
    SUBDOMAIN_REGISTER: "SUBDOMAIN_REGISTER",
    STANDARD_ASSET_MINT: "STANDARD_ASSET_MINT",
    STANDARD_ASSET_TYPE_CREATE: "STANDARD_ASSET_TYPE_CREATE"
};
module.exports = bizType;
